{
    "openapi": "3.0.1",
    "info": {
        "title": "Feedback Submissions",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "PUBLIC_BETA",
        "x-hubspot-api-use-case": "To prepare for an upcoming product redesign, programmatically retrieve all feedback survey responses to better understand customer sentiment.",
        "x-hubspot-related-documentation": [
            {
                "name": "Feedback Submissions Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/objects/feedback-submissions"
            }
        ],
        "x-hubspot-introduction": "Use the feedback submissions API to retrieve information submitted to your NPS, CSAT, CES, and custom feedback surveys."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/feedback_submissions"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read a batch of submissions",
                "operationId": "post-/crm/v3/objects/feedback_submissions/batch/read_read",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ],
                "description": "Returns a batch of feedback submission records matching the provided internal IDs or unique property values, with partial success indicated by a 207 response."
            }
        },
        "/{feedbackSubmissionId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Get a feedback submission",
                "description": "Read an Object identified by `{feedbackSubmissionId}`. `{feedbackSubmissionId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/feedback_submissions/{feedbackSubmissionId}_getById",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive a feedback submission",
                "description": "Move an Object identified by `{feedbackSubmissionId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/feedback_submissions/{feedbackSubmissionId}",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update a feedback submission",
                "description": "Perform a partial update of an Object identified by `{feedbackSubmissionId}`. `{feedbackSubmissionId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/feedback_submissions/{feedbackSubmissionId}",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of submissions",
                "operationId": "post-/crm/v3/objects/feedback_submissions/batch/archive",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ],
                "description": "Archives the specified feedback submissions and returns no content on success."
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of submissions",
                "operationId": "post-/crm/v3/objects/feedback_submissions/batch/create",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ],
                "description": "Returns a batch of newly created feedback submission objects, including their assigned IDs and properties. A 207 response indicates partial success."
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update a batch of submissions",
                "operationId": "post-/crm/v3/objects/feedback_submissions/batch/update",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ],
                "description": "Returns the updated feedback submission objects after applying the specified property changes. A 207 response indicates partial success."
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "List feedback submissions",
                "description": "Read a page of feedback submissions. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/feedback_submissions_getPage",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a feedback submission",
                "description": "Create a feedback submission with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard feedback submissions is provided.",
                "operationId": "post-/crm/v3/objects/feedback_submissions",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert a batch of submissions",
                "operationId": "post-/crm/v3/objects/feedback_submissions/batch/upsert",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ],
                "description": "Returns the created or updated feedback submission objects matched by unique property values. A 207 response indicates partial success."
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "operationId": "post-/crm/v3/objects/feedback_submissions/search_doSearch",
                "security": [
                    {
                        "oauth2_legacy": []
                    },
                    {
                        "private_apps_legacy": []
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ],
                "description": "Returns a paginated list of feedback submission objects matching the specified search criteria and filters.",
                "summary": "Search feedback submissions"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.services.read": "Read services",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.companies.write": " ",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.deals.write": " ",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.deals.read": " ",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.companies.read": " ",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.orders.read": "Read Orders"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "PUBLIC_BETA"
}